(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2014-12-22 14:51:53
  From session:  text
  Captured on:  2014-12-22 14:51:10
  From server:  Win-8 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

BeginTestCase "scrolling"
Click "FileTab"
Click "Settings"
MoveTo "SettingWIndow"
ScrollWheelDown 13.0
ScrollWheelUp 7.0
MoveTo "SettingWindow2"
--ScrollWheelUp 7.0
--Click (Image:"DownArrow", WaitFor:2)
--Click "DownArrow"
Click "SaveAndReturn"
EndTestCase "scrolling"

BeginTestCase "Close_app"
Click "bn_close"
Click (image:"bn_DontSave", waitFor:10)
EndTestCase "Close_app"